#############################################################################
#     Makefile for building Femocs executable for C main function
#############################################################################

include release/makefile.defs

all: release/femocs

release/femocs: release/femocs.o
	${CC} $< ${options} ${CCFLAGS} ${LFLAGS} -o $@

release/femocs.o: lib/libfemocs.a ${main_file}
	${CC} -c ${main_file} ${options} ${CCFLAGS} -o $@	

clean:
	rm -f release/femocs release/femocs.o include/*.o src/*.o

clean-all:
	rm -rf release/femocs release/femocs.o include/*.o src/*.o
