#############################################################################
#     Makefile for building Femocs executable for Fortran main function
#############################################################################

include release/makefile.defs

all: release/femocs

release/femocs: release/femocs.o
	${F90} $< ${OPT} ${CFLAGS} ${FCFLAGS} ${LFLAGS} ${EXTLFLAGS} -o $@

release/femocs.o: lib/libfemocs.a ${FMAIN}
	${F90} -c ${FMAIN} ${OPT} ${CFLAGS} ${FCFLAGS} -o $@

clean:
	rm -f release/femocs release/femocs.o include/*.o src/*.o

clean-all:
	rm -rf release/femocs release/femocs.o include/*.o src/*.o
