#############################################################################
#     Makefile for building Femocs executable for C main function
#############################################################################

include release/makefile.defs

all: release/femocs

release/femocs: release/femocs.o
	${CC} $< ${OPT} ${CCFLAGS} ${LFLAGS} -o $@

release/femocs.o: lib/libfemocs.a ${MAIN_C}
	${CC} -c ${MAIN_C} ${OPT} ${CCFLAGS} -o $@

clean:
	rm -f release/femocs release/femocs.o include/*.o src/*.o
    
clean-all:
	rm -rf release/femocs release/femocs.o include/*.o src/*.o
