#############################################################################
#     Makefile for building Femocs documentation in pdf and html format
#############################################################################

include release/makefile.defs

all: doc/femocs.pdf

doc/femocs.pdf:
	cd doc; doxygen femocs.doxyfile; cd latex; make; cp refman.pdf ../femocs.pdf

clean:
	rm -rf doc/html doc/latex doc/*.pdf

clean-all:
	rm -rf doc/html doc/latex doc/*.pdf
