#############################################################################
#               Makefile for building Femocs as library
#############################################################################

include release/makefile.defs

all: lib/libfemocs.a

lib/libfemocs.a: lib/build/Makefile lib/libtet.a src/* include/* 
	cd lib/build; make -j${NPROCS}

lib/build/Makefile: dealii/lib/libdeal_II.a
	cd lib; mkdir -p build; cd build; rm * -r; cmake -DCMAKE_Fortran_COMPILER=${F90} ..

lib/libtet.a:
	make -f release/makefile.install
	
dealii/lib/libdeal_II.a:
	make -f release/makefile.install

clean:
	rm -f lib/libfemocs.a lib/libfemocs.mod lib/build/Makefile
	
clean-all:
	rm -rf lib/libfemocs.a lib/libfemocs.mod lib/build
